### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by cosdy** [yanzhenjie/album#10]
将选择好的图片上传到阿里云的 oss 服务，但由于上传的原图太大了，上传很慢！请问该怎么处理？谢谢！

**Comment by yanzhenjie** [comment]
对原图惊醒剪切或者压缩后再上传，有很多开源项目可以剪切的。我目前使用的是下面这个项目：[https://github.com/Yalantis/uCrop](https://github.com/Yalantis/uCrop)
