### ISSUE TITLE
混淆方案

### ISSUE THREAD

**Issue by Reginer** [yanzhenjie/Album#100]
现在提供的混淆方案是不对的。
Album的混淆方案就是NoFragment的混淆方案，同时NoFragment的混淆方案需要改进。
因为原生Fragment是支持混淆的。方案是 
-keep public class * extends com.yanzhenjie.fragment.NoFragment

**Comment by Reginer** [comment]
现有的混淆方案错误就会导致 #85

**Comment by yanzhenjie** [comment]
在做测试时全部混淆后没有出现问题，我们并没有keep任何类，你那边是所有手机必现还是？

**Comment by Reginer** [comment]
这个问题其实是必现的。你想想，Album里面用到了NoFragment，NoFragment里面用到了反射Fragment的方法，原生Fragment又是会被混淆的。 只需要按我给出的混淆方案即可

**Comment by yanzhenjie** [comment]
好的。

**Comment by yanzhenjie** [comment]
我刚刚做了测试，没有对NoFragment做任何keep，在以下系统版本通过测试：
* 4.4.4 模拟器
* 6.0.1 小米
* 6.0 模拟器
* 7.0 模拟器
* 4.2.2 oppo
* 6.0.1三星
测试了Album所有的功能点，均没有出现问题，应该不是NoFragment混淆的问题。  
NoFragment使用了反射获取类示例，但是混淆后类名变化，那么`XFragment.class.getName();`也会跟着发生变化，应该不是这个问题，#85我怀疑是被系统回收或者开发者设置Widget为null。

**Comment by Reginer** [comment]
你是没对 NoFragment做keep，但是你keep了原生的Fragment。在安卓里Fragment是允许被混淆的。

**Comment by yanzhenjie** [comment]
我刚才又测试了一遍，对Fragment做了完全混淆，但是还是没有出现任何错误，下面是我测试时的配置和情况：
（另外我也做了activity被系统回收的测试，这里有点问题，就是不能回调结果到被回收的activity，这个对于目前的api设计，我暂时没有想到好的办法，但是不会造成崩溃。）

1. 这是反编译后的Fragment被混淆的代码：
![support](https://user-images.githubusercontent.com/13534988/32588993-1c26d8ca-c54d-11e7-9cd4-caf3773871a4.png)

2. 这是NoFragment被混淆的代码：
![fragment](https://user-images.githubusercontent.com/13534988/32589051-56675898-c54d-11e7-9c3a-6e9125d5b676.png)

3. 这是我的测试build配置：
![build](https://user-images.githubusercontent.com/13534988/32589053-5ce62c94-c54d-11e7-9287-7e8fd1a8138e.png)

4. 这是我的混淆规则：
![pro](https://user-images.githubusercontent.com/13534988/32589058-616ff768-c54d-11e7-8886-efd16b5f4003.jpg)

5. 这是Album运行时Layout Inspector的截图：
![inspector](https://user-images.githubusercontent.com/13534988/32589129-b97cb48c-c54d-11e7-9374-ecced51281da.png)

**Comment by Reginer** [comment]
现在的版本确实不需要这个混淆方案了。记得出现问题的是2.0.0-alpha

**Comment by yanzhenjie** [comment]
那应该在2.0.0正式版就不会出现了，你发问题的时候已经是2.0.1了，所以说岔了。刚刚发布了2.0.2，修复了些大家提的bug，也优化了一些逻辑。

**Comment by Reginer** [comment]
嗯，看到有个那种bug顺便发一下。
