### ISSUE TITLE
能否将缓存目录AlbumCache缓存的图片去除格式

### ISSUE THREAD

**Issue by starlightjy** [yanzhenjie/Album#101]
缓存图在系统相册或者其他第三方相册浏览中，又会增加一个目录也就是AlbumCache文件中的很多低清图，这很多余，可否删除，或者去掉文件后缀、或者增加后缀，使其不会在其他相册中出现？当然这只是个建议~~~

**Comment by yanzhenjie** [comment]
Album2.0.1版本也会出现这个问题吗？如果是因为2.0.0版本造成的，请删除`AlbumCache`文件夹，然后再次打开Album2.0.1版本应该就不会出现了，如果还是出现请告之我，我要做一下优化。

**Comment by starlightjy** [comment]
是的，我用的是2.0.1版本的：
compile 'com.yanzhenjie:album:2.0.1'
还是会出现AlbumCache文件夹，多选完图片后产生对应缩略图
PS:魅族手机Flyme6，夜神模拟器安卓版本4.4.2均会出现

**Comment by yanzhenjie** [comment]
这个文件夹是肯定会出现的，只要在相册内不出现就没问题吧。
