### ISSUE TITLE
摄像指定的filepath路径,并没有效果

### ISSUE THREAD

**Issue by OvenCroc** [yanzhenjie/Album#103]
`Album.camera((BaseActivity) webview.getContext())
                                    .video()
                                    .filePath(AppCons.VIDEO_PATH)
                                    .start();`
这里设置了文件路径是...../demo.mp4, onaction回调返回的也确实是这个路径 但是这个路径下面根本没有视频

**Comment by 6Weiqi** [comment]
我也遇到相同的问题，请问解决了吗？
