### ISSUE TITLE
图片选择框AppCompatCheckBox点击区域如何调大一点

### ISSUE THREAD

**Issue by starlightjy** [yanzhenjie/Album#108]
因为使用Gradle,所以没法直接修改源代码，选择图片的时候，右上角的那个CheckBox的点击区域太小了，经常被吐槽点了就到大图查看页面了。。。

**Comment by yanzhenjie** [comment]
刚刚发布了新版本2.0.2，把CheckBox放大了，同时解决了现在大家提的一些bug和不完善的逻辑，同时更新了support库为26.1.0，你更新新版本试试看。
