### ISSUE TITLE
BUG,建议

### ISSUE THREAD

**Issue by fairytale110** [yanzhenjie/Album#109]
BUG: 华为 ATJ-AL000手机，Android 6.0.1，从demo 的视频按钮调用系统相机录制视频，一点录制按钮就提示“已到达大小限制”

建议：加入视频播放，不然只是一张预览图，会不会不是很好呢，可以参阅[Phoenix](https://github.com/guoxiaoxing/phoenix)，我觉得你们俩可以融合一下，他的图片拍摄处理和视频播放做的还可以，就是不能拍摄视频，只是个人观点，：）

**Comment by fairytale110** [comment]
BUG已解决：
 Album.camera(this)
 .video()
//                .limitDuration(Long.MAX_VALUE)
//                .limitBytes(Long.MAX_VALUE)
                .limitDuration(1000*60*10)
                .limitBytes(1024*1024*10)

**Comment by yanzhenjie** [comment]
`limitBytes()`默认是`Long.MAX_VALUE`，部分手机上会提示“已达大小限制”，设置`limitBytes()`为`Integer.MAX_VALUE`即可解决。
