### ISSUE TITLE
 Unable to destroy activity com.yanzhenjie.album.ui.AlbumActivity

### ISSUE THREAD

**Issue by ljackChen001** [yanzhenjie/Album#111]
选择相册时可以打开，关闭（返回按钮和物理返回）AlbumActivity时都要崩溃！
![tim 20171027160908](https://user-images.githubusercontent.com/13534229/32094083-3693c478-bb31-11e7-8216-ed7fe50b584d.jpg)

**Comment by yanzhenjie** [comment]
Album中没有中文异常，这个错似乎是回去后，你后面的代码报错了。
