### ISSUE TITLE
加载图片慢 读取1W张图片需30s

### ISSUE THREAD

**Issue by zhouchaohao** [yanzhenjie/Album#115]
加载图片慢 读取1W张图片需30s

**Comment by yanzhenjie** [comment]
是2.0.1版本吗？如果是2.0.0-alpha的话，升级一下就可以了。如果是2.0.1版本这么慢，那我也没办法再优化了，希望其它看到的同学能提供下更优的加载方案。

**Comment by sweet2o09** [comment]
@yanzhenjie 我之前是有做过一个扫描铃声的,效率还挺高,我想扫描图片跟视频应该也差不多
链接：http://pan.baidu.com/s/1i5zRk9n 密码：zmqm
如果作者感兴趣的话可以拿去参考下,代码写得不好

**Comment by yanzhenjie** [comment]
@zhouchaohao 照片多了任何框架都会慢的，Album因为返回的字段多，所以查询的字段也多一点，想比其它同类型框架可能稍微慢一点点，我再优化一下逻辑算法，请关注新版本。

@sweet2o09 感谢反馈，我看了你的代码，查询多媒体库都是搜索数据库，Album查询的字段多，而且做了分类和排序所以慢，我会再优化一下加载算法，请关注新版本。

**Comment by sweet2o09** [comment]
@zhouchaohao 我这边用2.0.2版本看,1W张要35秒才加载出来,我还是只选择图片,没有选择视频,不知道你那边用最新版本是否有提高读取速度

**Comment by sweet2o09** [comment]
@yanzhenjie 你好,我这边有一台小米手机,里面存放4千张图片,启动页需要30秒,估计是目录结构比较复杂,不过还是十分感谢你的这个框架,非常好用,谢谢
