### ISSUE TITLE
Camera拍照的图片不能在相册中展示

### ISSUE THREAD

**Issue by liukai2530533** [yanzhenjie/Album#117]
Camera拍照的图片之后设置为.checkedList（list） 中的已选中的条件 然后它不能展示出来 本地相册也找不到该图片 就算设置了  Album.camera(context).filePath(path) 设置之后也不能作为已选中的条件展示出来，我是老用户 。1.0的版本是可以的，1.0版本拍完照片立马就能在相册中展示，并且能设置为已选择的条件默认√上

**Comment by yanzhenjie** [comment]
总结一下问题，看不太明白。
1. 拍照不管是否设置的path，给你的路径总是String，选照片/视频返回给你的是`ArrayList<AlbumFile>`,而选择照片是需要反选的对象是`ArrayList<AlbumFile>`，如果再次选照片时需要反选，上次选择返回给你的图片是没问题的，如果需要反选拍照返回甚至是某个路径的图片，需要`new AlbumFile()`，然后设置AlbumFile的路径为你想反选的图片的路劲。
2. 现在的版本拍摄后是会立即选中当前拍的视频或者图片的。
如果还有问题，麻烦你再描述详细一点回复一下。

**Comment by bigwangoo** [comment]
问题是这样，比如9张图，单独调用相机拍一张，然后去再调用相册选取图片，结果相册里没有刚才相机拍的那张

**Comment by yanzhenjie** [comment]
单独调用相机功能，仅仅是调用相机拍照功能，把拍照返回，和相册无关，所以不出现。如果是在相册中调用的，Album会加到相册中。

如果开发者想单独调用相机后还想加到相册中，需要自己加。
