### ISSUE TITLE
能否指定缓存的目录？

### ISSUE THREAD

**Issue by 6Weiqi** [yanzhenjie/Album#119]

**Comment by yanzhenjie** [comment]
请参考[高级初始化](https://github.com/yanzhenjie/NoHttp#高级初始化)。

**Comment by 6Weiqi** [comment]
noHttp?

**Comment by yanzhenjie** [comment]
Sorry，issue太多了我搞混了，以为是NoHttp下的了，缓存目录是不能配置的，这是针对全系统所有App的优化。
