### ISSUE TITLE
album图片和视频混合选择模式下，录制视频无法指定文件路径

### ISSUE THREAD

**Issue by gruffwy** [yanzhenjie/Album#123]
这时候手机要是没SD卡就尴尬了，无法拍视频，会一直提示“已达到大小上限”

**Comment by yanzhenjie** [comment]
默认使用的`Long.MAC_VALUE`作为限制，在部分手机上会有上述问题，开发者可以指定文件大小、时间限制：
```java
.cameraVideoQuality(1)
.cameraVideoLimitDuration(Integer.MAX_VALUE)
.cameraVideoLimitBytes()(Integer.MAX_VALUE)
```

**Comment by gruffwy** [comment]
改了一下确实可以录像了，但还是建议在所有模式下都加入指定filePath功能，在一些老版本android无sd卡手机中，自动获取的path不太合理

**Comment by yanzhenjie** [comment]
在相册里面是相册行为，不是开发者行为，所以不能指定路径，而且可以拍摄很多视频和照片。没有SD卡的这种情况在下个版本我会做好兼容。
