### ISSUE TITLE
集成出现问题啊。。。

### ISSUE THREAD

**Issue by jameschou51** [yanzhenjie/Album#131]
Error:Could not find com.android.support:appcompat-v7:26.1.0.
Required by:
    project :app
    project :app > com.yanzhenjie:album:2.0.2

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by FriendLin** [comment]
# 依赖
  * Gradle：
  ```groovy
 -compile 'com.yanzhenjie:album:2.0.1'
 +compile 'com.yanzhenjie:album:2.0.2'
  ```
  
  * Maven:
  ```xml
  <dependency>
    <groupId>com.yanzhenjie</groupId>
    <artifactId>album</artifactId>
 -  <version>2.0.1</version>
 +  <version>2.0.2</version>
    <type>pom</type>
  </dependency>
  ```
  
 -> 本库使用的`support`库的版本为`25.3.1`，如果引入的`support`库版本高于`25.3.1`，请明确指定`CardView`的版本或者使用`exlude`语法过滤。

以上是作者的原话(提交记录里可以看到) ，请尝试降低一下版本试试 ，我的 support库是 25.3.1  2.0.1可以了
