### ISSUE TITLE
Video not working..

### ISSUE THREAD

**Issue by lizarazu77** [yanzhenjie/Album#133]
hi...

i'm razi from malaysia..i already downloaded you Album source code from Github.com
the sample program look cool...the feature easy to used it..

But i got problem when run in Huawei Ep820 (Handset/Handheld)...
the problem is when i click on Album and click Take Video..when press record button
Toast "Size limit reached"...btw i already change save to location to Internal Storage...

Any idea?

**Comment by yanzhenjie** [comment]
1. Use Album:
```java
Album.album(this)
    .multipleChoice()
    .camera(true)
    .cameraVideoLimitBytes(...) // Specify the file size, which is part of the phone's bug
    ...;
```
2. Use video:
```java
Album.video(this)
    .multipleChoice()
    .camera(true)
    .limitBytes(...) // Specify the file size, which is part of the phone's bug
    ...;
```

3. Use camera:
```java
Album.camera(this)
    .video()
    .limitBytes(...) // Specify the file size, which is part of the phone's bug
    ...;
```

**Comment by lizarazu77** [comment]
Album.camera work fine..
but  when you using

Album.album(this)
                .multipleChoice()
                .requestCode(200)
                .columnCount(2)
                .selectCount(6)
                .camera(true)
                .cameraVideoQuality(1)....

got problem...so any suggestion/example limitbytes using?

**Comment by yanzhenjie** [comment]
Time and file size is proportional to the general we only choose one to use, it is recommended to limit the time, video recording is completed, the use of ffmpeg or any libraries to compress the video.

**Comment by lizarazu77** [comment]
Work Fine with 2 below code...

Album.camera(this)
    .video()
    .limitBytes(Integer.MAX_VALUE) // Specify the file size, which is part of the phone's bug
    ...;

Album.video(this)
                .multipleChoice()
                .requestCode(200)
                .columnCount(2)
                .selectCount(6)
                .camera(true)
                .limitBytes(Integer.MAX_VALUE )

**Comment by yanzhenjie** [comment]
The above three examples are possible to use, after our test is no problem, if you have any questions, trouble you to feedback to us.
In addition, it is very welcome to submit the PR to participate in the development of this project.
