### ISSUE TITLE
选择完图片之后为什么显示不出来

### ISSUE THREAD

**Issue by lnrelax** [yanzhenjie/Album#148]
该copy的文件都已经copy，但是就是不显示，其实已经获取到了

**Comment by liukai2530533** [comment]
![test](https://user-images.githubusercontent.com/23752905/41396701-610d3c8a-6fe4-11e8-9641-b6e5c4fdbda0.png)

**Comment by liukai2530533** [comment]
是不是这个效果。我把作者的代码全部copy过来都显示不出来 怎么搞

**Comment by yanzhenjie** [comment]
你们好，认证看看ReadMe，写的非常清楚。如果结合demo还不好使，说明这个框架有极大的bug，你们可以换其他框架使用，谢谢反馈！
