### ISSUE TITLE
一个崩溃信息

### ISSUE THREAD

**Issue by imliujun** [yanzhenjie/Album#153]
![image](https://user-images.githubusercontent.com/9779970/36626345-199cfc9c-196c-11e8-886e-7f93e47fc156.png)

**Comment by yanzhenjie** [comment]
是哪个版本？

**Comment by imliujun** [comment]
>"com.yanzhenjie:album:2.0.2"

**Comment by imliujun** [comment]
**还有几个异常信息：**

![image](https://user-images.githubusercontent.com/9779970/36627448-d8ed5e5a-197d-11e8-9095-a957e5b122fe.png)


![image](https://user-images.githubusercontent.com/9779970/36627475-4e16b514-197e-11e8-84fd-5a6b952e1171.png)

![image](https://user-images.githubusercontent.com/9779970/36627662-dd9eb5ae-1980-11e8-86f5-ebf0b7ca4786.png)
