### ISSUE TITLE
选择图片下标越界异常

### ISSUE THREAD

**Issue by jyrwm** [yanzhenjie/Album#16]
选择一张图片后返回，点击眼睛图标查看，个人感觉对勾出来的有点慢了，点击选择，demo崩溃，下标越界异常；

**Comment by jyrwm** [comment]
![qq 20170330145801](https://cloud.githubusercontent.com/assets/16571734/24491708/0c767aa4-155b-11e7-81e5-677b70dc06ba.png)

**Comment by ssyijiu** [comment]
@jyrwm 请教一下你用的什么工具可以直接看 crash

**Comment by yanzhenjie** [comment]
@jyrwm 已确认是一个bug：  
选择照片后，点击眼睛预览已经选择的大图，点击后，手指快速再次点击会点击到第二个页面的复选框，此时由于太快，选中的数据没更新，导致崩溃。
当然手机正常点击暂时没发现问题，正在修复。
