### ISSUE TITLE
filterSize

### ISSUE THREAD

**Issue by Yzdream** [yanzhenjie/Album#161]
filterSize()筛选参数怎么填呢，比如我不要500kb以上的图片

**Comment by ycx974577817** [comment]
Album.album(this)
                    .singleChoice()
                    .filterSize { it<500*1024 }
                    .onResult { requestCode, result ->  }
                    .start()

**Comment by Yzdream** [comment]
谢谢严大，看了下源码，已经处理了，建议你在文档上加上说明，感谢严大回复。




------------------ 原始邮件 ------------------
发件人: "ycx974577817"<notifications@github.com>;
发送时间: 2018年4月15日(星期天) 晚上10:59
收件人: "yanzhenjie/Album"<Album@noreply.github.com>;
抄送: "易正"<714570221@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yanzhenjie/Album] filterSize (#161)



        Album.album(this)                 .singleChoice()                 .filterSize { it<500*1024 }                 .onResult { requestCode, result ->  }                 .start()
