### ISSUE TITLE
Bug in ImageGallery not firsttime receive image

### ISSUE THREAD

**Issue by Paul75** [yanzhenjie/Album#164]
Hello,

It strange error : when first start activity and in a button add to start seelct or take picture and  chose photo and validate nothing appear in the result activity.
I go back to activity and do same and when validate choice photos appears ....

Here link with my video exemple : https://drive.google.com/open?id=1qhnCp9ukk-j0K_D0el67Y2Ko_icjhd_b

Any help ?

**Comment by yanzhenjie** [comment]
Maybe you copied the code in the sample, the ImageView in the sample is calculated by DisplayUtils, and DisplayUtils needs to be initialized.
Solution: You should only use Album to accept the file path. Image loading should not refer to sample.

**Comment by Paul75** [comment]
Not understand correctly ....Sorry

**Comment by yanzhenjie** [comment]
Is this your problem?
> After selecting an image from **Album** and returning to your App, the image cannot be displayed in the App.

**Comment by Paul75** [comment]
yes

**Comment by Paul75** [comment]
ok understand. I add : DisplayUtils.initScreen(this); into MainActivity and now works ...

**Comment by yanzhenjie** [comment]
Yeah. Although this works fine, I do not recommend using DisplayUtils. The next version will be deprecated. I am refactoring a new version and it will be released soon.
