### ISSUE TITLE
我自己调用拍照之后，用MediaScanner手动刷新相册为何再次进去相册选择没有那张图

### ISSUE THREAD

**Issue by Yuphee** [yanzhenjie/Album#175]
Album.camera(this) 
                              .image()
                              .filePath(PathUtils.getYzNewsImgPath() + File.separator + System.currentTimeMillis())
                              .requestCode(TAKE_REQ)
                              .onResult((requestCode, result) -> {
                                    MediaScanner scanner = new MediaScanner(PublishActivity.this);
                                    scanner.scan(file);
                                    AlbumFile af = new AlbumFile();
                                    af.setPath(result);
                                    mAlbumFiles.add(af);    
                                })
                              .onCancel((requestCode, result) -> {
                                })
                              .start();

**Comment by yanzhenjie** [comment]
这里应该写图片路径。
```
scanner.scan(file);
```

**Comment by Yuphee** [comment]
我知道了保存图片必须以图片格式结尾不然扫描不到
