### ISSUE TITLE
正在创建缩略图，然后就一直创建，也不能取消

### ISSUE THREAD

**Issue by Reginer** [yanzhenjie/Album#179]
这个创建缩略图是在干啥？应用没有写sd卡权限。
另外内存卡下那个AlbumCache文件夹是否支持配置到其他地方？
或者设计为默认放在应用缓存路径下？
版本2.1.1，安卓版本8.0，华为EMUI8.0
![default](https://user-images.githubusercontent.com/12568257/39753021-f6466e78-52ef-11e8-87d1-2ecda9de47f4.png)

**Comment by yanzhenjie** [comment]
必须要有SD卡的读写权限。这个缓存目录是Album内置loader为所有使用Album的app加速的，现在loader必须被外部配置，因此下个版本允许配置到别的位置。

**Comment by Reginer** [comment]
我改了[这个文件](https://github.com/yanzhenjie/Album/blob/master/album/src/main/java/com/yanzhenjie/album/util/AlbumUtils.java)的`getAlbumRootPath(Context context)`之后引用aar可以了。支持修改路径之后再close吧，我还能收到通知，及时改成网络引用
