### ISSUE TITLE
Image list showing only white background not images

### ISSUE THREAD

**Issue by jeevatech** [yanzhenjie/Album#188]
I have tried using your Album library(2.1.1) but it showing only white space not the images(preview), But it is working perfectly in version 2.0.2.

Here is my code

```
Album.image(ImageUploaderUtil.this) 
                        .multipleChoice()
                        .camera(true)
                        .columnCount(3)
                        .selectCount(5)
                        .checkedList(multipleChoiceAlbumFiles)
                        .onResult(new Action<ArrayList<AlbumFile>>() {
                            @Override
                            public void onAction(@NonNull ArrayList<AlbumFile> result) {

                                multipleChoiceAlbumFiles=result;
                                for(AlbumFile file:multipleChoiceAlbumFiles)
                                {
                                    Toast.makeText(ImageUploaderUtil.this,"Image Path"+file.getPath(),Toast.LENGTH_LONG).show();
                                }

                            }
                        })
                        .onCancel(new Action<String>() {
                            @Override
                            public void onAction(@NonNull String result) {
                            }
                        })
                        .start(); 
```

attached the screen below
![screenshot_20180518-135126](https://user-images.githubusercontent.com/39401676/40224122-dad9cc92-5aa2-11e8-819a-8358b92baa9b.png)

**Comment by wang-yan-ting** [comment]
I have same issue, please help to fix it.

**Comment by yanzhenjie** [comment]
You need to [configure the loader](https://github.com/yanzhenjie/Album#configuration-loader).

**Comment by wang-yan-ting** [comment]
I can not see why my loader not work.

```

public class MediaLoader implements AlbumLoader {

    @Override
    public void load(ImageView imageView, AlbumFile albumFile) {
        load(imageView, albumFile.getPath());
    }

    @Override
    public void load(ImageView imageView, String url) {
        Picasso.with(imageView.getContext())
                .load(url)
                .fit()
                .centerCrop()
                .placeholder(R.mipmap.icon_device_administrator)
                .error(R.mipmap.icon_device_administrator)
                .into(imageView);
    }
}

```

**Comment by mekotlin** [comment]
i am facing same issues, please fix it.

**Comment by padi-dev-nganq** [comment]
i have same issue please help me
public class MediaLoader implements AlbumLoader {

    @Override
    public void load(ImageView imageView, AlbumFile albumFile) {
        load(imageView, albumFile.getPath());
    }

    @Override
    public void load(ImageView imageView, String url) {
        Glide.with(imageView.getContext())
                .load(new File(url))
                .error(R.drawable.ic_launcher)
                .placeholder(R.drawable.ic_launcher)
                .into(imageView);
    }
}

**Comment by Zennaxxtech** [comment]
I have fixed this issue by adding below code. Just call this below method in your `onCreate()` method.


```
private void initializeAlbum() {
        Album.initialize(AlbumConfig.newBuilder(this)
                .setAlbumLoader(new MediaLoader())
                .build());
    }
```
Also add this below code in your Activity class

```
public class MediaLoader implements AlbumLoader {

        @Override
        public void load(ImageView imageView, AlbumFile albumFile) {
            load(imageView, albumFile.getPath());
        }

        @Override
        public void load(ImageView imageView, String url) {
            Glide.with(imageView.getContext())
                    .load(url)
                    //.error(R.drawable.placeholder)
                    //.placeholder(R.drawable.placeholder)
                    //.crossFade()
                    .into(imageView);
        }
    }
```

**Comment by ghost** [comment]
I also get same issue , but could not getted to resolve , can anyone help to me thanks in advance

**Comment by MrHeshamYemen** [comment]
I also get same issue

**Comment by MrHeshamYemen** [comment]
I found the solution 
the problem is because of Glide library with Android 10 ( Android Q ) 
Glide can't access local storage 
so

the solution is sample just add this line in Manifest file 

<application 
 ....
  android:requestLegacyExternalStorage="true"
