### ISSUE TITLE
4.4.4版本手机

### ISSUE THREAD

**Issue by daiwuzhou** [yanzhenjie/Album#19]
在Android 系统版本4.4.4的手机上点开大图没有后退按键栏目

**Comment by yanzhenjie** [comment]
请问是使用Album1.0.0吗？1.0.0版本可能存在这个问题，请升级到1.0.2，升级后请反馈下结果，谢谢。

**Comment by daiwuzhou** [comment]
用的是1.0.2的。现在的手机的系统的ColorOS ，在模拟器5.1.1上是正常的

**Comment by yanzhenjie** [comment]
请提供一下详细的环境信息。

**Comment by daiwuzhou** [comment]
用的album的1.0.2，手机是一加手机一代，系统是Android 4.4.4的ColorOS，

**Comment by yanzhenjie** [comment]
忘记来回复了，这个问题后来修复了，1.0.5就修复了，昨晚已经发布了1.0.7了，你可以使用新版看看。
