### ISSUE TITLE
.start()启动api 不显示图片  都是空白的    有遇到过吗 魅族pro6

### ISSUE THREAD

**Issue by androidjanuary** [yanzhenjie/Album#190]

**Comment by yanzhenjie** [comment]
2.1.1版本需要配置Loader，参考首页的说明。

**Comment by GirlFriendNotFind** [comment]
配置了也没显示？？只显示配置的加载错误图片

**Comment by liukai2530533** [comment]
@androidjanuary 我也遇到过这个问题 以前都是使用2.0.2 显示升级2.1.2图片都是白色 设置Loader也是这样

![test](https://user-images.githubusercontent.com/23752905/41394806-f3815314-6fdd-11e8-89c9-62a8128656f8.png)

**Comment by yanzhenjie** [comment]
这种问题参考下demo就好了，别提了。
