### ISSUE TITLE
colorPrimary为白色背景工具栏的时候

### ISSUE THREAD

**Issue by qiaoyj** [yanzhenjie/Album#20]
colorPrimary为白色的时候，工具栏的导航图标、标题以及菜单字体颜色都是白色，看不见。
建议作者是用可自定义的toolbar做为工具栏。

**Comment by yanzhenjie** [comment]
不推荐白色，因为部分国产手机bug，设置白色状态栏时不会按照系统规则把图标变为深色，华为，小米都是，所以Album也没有做这个支持。

**Comment by qiaoyj** [comment]
我是白色工具栏，黑色状态栏。（小米和魅族是可以设置状态栏图标和文字颜色的，这个不纠结）。现在也有好多APP是白色的工具栏，如腾讯新闻、百度地图等。希望作者以后对白色工具栏做支持，可以改变导航图标、标题以及菜单字体颜色

**Comment by yanzhenjie** [comment]
刚刚发布了2.0-alpha版本，支持白色状态栏，我们公司已经在使用了，2.0变化比较大，你可以试试2.0，用流式API的实行提供了各种功能，包括视频选择，拍视频等。
