### ISSUE TITLE
如何控制不让那些没有后缀名得图片在图片选择得时候出现？

### ISSUE THREAD

**Issue by Yuphee** [yanzhenjie/Album#202]
我发现把一些是图片但是经过加密去除后缀名之后放在了手机图片文件夹下面，然后选择照片就把它给显示出来了,这个怎么控制补显示这张图

**Comment by yanzhenjie** [comment]
通过mimeType，看一下文档。

**Comment by Yuphee** [comment]
我看mimeType返回就一个jpg如何限制
