### ISSUE TITLE
拍照异常

### ISSUE THREAD

**Issue by xicong** [yanzhenjie/Album#204]
![image](https://user-images.githubusercontent.com/11675597/42487856-7944daa0-8435-11e8-8329-e4af1d9dcd09.png)

**Comment by GeekTR** [comment]
+1

**Comment by GeekTR** [comment]
荣耀部分手机，vivo部分手机有这个异常

**Comment by yanzhenjie** [comment]
没有权限，因为Album是按照表示权限流程来请求权限的，所以在权限有问题的国产手机上可能会出现这个问题。你们在打开时强制获取一下相关权限即可，可以使用AndPermission。

**Comment by GeekTR** [comment]
建议在AlbumUtils.takeImage方法和takeVideo方法中调用startActivityForResult时catch一下异常并提醒手动开启权限
