### ISSUE TITLE
删除后还是显示在列表内，重新安装了也一样，如何清除？？

### ISSUE THREAD

**Issue by 1913656443** [yanzhenjie/Album#211]
删除目录内的图片后，列表内还是会显示，而且是白色，选了也没用，如何将这些无用的图片筛选掉？？？

**Comment by lexluthors** [comment]
我也是，图片损坏了还是显示。

**Comment by yanzhenjie** [comment]
图片信息是保存在手机的多媒体库中，比如你使用系统相机拍照后在可以看到，但是你自己保存一张图片到SD卡，在SD卡看不到，除非做一下media扫描加入系统多媒体库。因此图片被从SD卡删除时同样的道理，大部分手机会自动从多媒体库移除这个图片，但是一部分手机没有移除机会发生 @1913656443 的问题。你可以判断文件是否存在来解决，原来在内部判断了文件是否存在，但是这样会造成Album打开较慢的问题。

@lexluthors 图片损坏是文件数据问题，属于业务问题。

**Comment by lexluthors** [comment]
@yanzhenjie 谢谢

**Comment by 1913656443** [comment]
@yanzhenjie 谢谢
