### ISSUE TITLE
拍照获取图片均是横屏的？？？

### ISSUE THREAD

**Issue by oyl1love** [yanzhenjie/Album#214]
onlypictures
竖着拍照，显示在本地是正常的，上传后，获取的是横屏的，横屏的拍没问题，手机自带相机的照片没问题
求解决
  file1 = new File(mAlbumFiles.get(0).getPath());  //上传file

 Album.getAlbumConfig().
                        getAlbumLoader().
                        load(tgImgIv, mAlbumFiles.get(0));//本地加载方法

**Comment by yanzhenjie** [comment]
图片也是文件，但是图片有图片的属性，某些手机拍的图片本身方向不一定是拍时的摆设方向，拍完照需要读取图片角度来旋转图片以正常显示，本地加载时做了这样的处理所以是正常的。

**Comment by oyl1love** [comment]
可以发一下处理方法吗？刚才找了一下，只找到了load接口那，没看到方法

**Comment by sunlightAndroid** [comment]
检查一下是不是因为对图片进行压缩，压缩处理有问题导致旋转的，而不是Album的问题
