### ISSUE TITLE
.downloading后缀名图片类型过滤问题

### ISSUE THREAD

**Issue by rebertBen** [yanzhenjie/Album#216]
大神，图片相册选择中，引用的Album，这种图片如何过滤掉，后缀名为 .downloading。求解
华为手机，选择图片后，返回的图片信息：
mBucketName=“download”
mMimeType="image/jpeg"
mPath="/storage/emulated/0/Huawei/MagazineUpdate/download/magazine-unlock-hi1179002.downloading"
mThumbPath=null

如何设置这种图片在相册中不显示？

**Comment by yanzhenjie** [comment]
使用Filter，具体请参考ReadMe说明。
