### ISSUE TITLE
BaseActivity的onRequestPermissionsResult中调用isGrantedResult的参数传递错误

### ISSUE THREAD

**Issue by TpOut** [yanzhenjie/Album#217]
2.1.2的包
位置如题，
调用了isGrantedResult(requestCode)
应该是isGrantedResult(grantResults)
不然就算拒绝了，按照现有的逻辑，也会走onPermissionGranted
然后造成崩溃

**Comment by wudafei** [comment]
@Override
    public final void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        if (isGrantedResult(requestCode)) onPermissionGranted(requestCode);
        else onPermissionDenied(requestCode);
    }

**Comment by yanzhenjie** [comment]
This has been fixed in #229.
