### ISSUE TITLE
图库异常

### ISSUE THREAD

**Issue by zhengzaihong** [yanzhenjie/Album#239]
kotlin环境       java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yanzhenjie/album/app/album/AlbumActivity;异常  java环境能正常使用

**Comment by yanzhenjie** [comment]
只能提供一个解决思虑，最可能就是方法64k问题。
这类问题都是项目环境问题，非本库问题，请自行解决。

**Comment by zhengzaihong** [comment]
谢谢，问题已经排查出来，原因是本库使用了Android Arch LifeCycle ,而在support 组件下 25.xx.xx中还没支持，导致无法访问LifecycleOwner 出现的错误。只是这异常抛的不明显。尴尬！！解决办法 升级到 26.1.xx 以上！！
