### ISSUE TITLE
编译版本为23导入出错

### ISSUE THREAD

**Issue by yangzhenqi** [yanzhenjie/Album#24]
`compileSdkVersion 23`
当编译版本为23时，项目报错
![qq 20170412135248](https://cloud.githubusercontent.com/assets/11497068/24943186/e598b370-1f87-11e7-9b17-6dbbc8a5f778.png)

**Comment by yanzhenjie** [comment]
请看原项目的版本：  
```groovy
compileSdkVersion 25  
buildToolsVersion "25.0.2"  

supprot-library: 25.3.0
```
因为使用的了support的`appcompat`、`design`、`recyclerview`库，所以你的版本不能低于这个版本。
