### ISSUE TITLE
album.gallery()使用widget的时候，设置标题栏的背景色不起作用，这样的图片放大后，会看不清返回按钮

### ISSUE THREAD

**Issue by Founder005** [yanzhenjie/Album#246]

**Comment by Founder005** [comment]
`  ArrayList<String> list = new ArrayList<>();
                    list.add(imagePath);
                    Widget widget = Widget.newDarkBuilder(mContext).title("查看图片").statusBarColor(getResources().getColor(R.color.title_bg_color)).toolBarColor(getResources().getColor(R.color.colorAccent)).build();
                    Album.gallery(mContext)
                            .widget(widget)
                            .checkedList(list) // List of image to view: ArrayList<String>.
                            .start();`

**Comment by yanzhenjie** [comment]
库就是这么设计的，有个半透明，要是不喜欢就自己改一下用吧。
