### ISSUE TITLE
flyme 系统适配问题

### ISSUE THREAD

**Issue by langaoyang** [yanzhenjie/Album#25]
测试机型  ：   mx4pro ,flyme 6.02   
问题1: 点击选择框 动画不流畅 。选中图片,点击图片进入图片查看的界面。下面的选择框 动画进行完成不了。 这个回头可以发个录屏给你。
2.没有沉浸式状态栏。

**Comment by langaoyang** [comment]
studio 自带模拟器上没有问题1 。

**Comment by yanzhenjie** [comment]
@langaoyang 请问Android系统版本是多少？你可以录个视频发我邮箱或者传我QQ都可以：`smallajax@foxmail.com`，谢谢反馈。

**Comment by langaoyang** [comment]
好的。我发你邮箱吧。邮箱应该会好一点。

**Comment by yanzhenjie** [comment]
你好，请问有发我邮件吗？我似乎没有收到，谢谢。

**Comment by langaoyang** [comment]
当天就发了。我重新发送一下好了

**Comment by langaoyang** [comment]
已发送，如果还是没有说到，你检查你邮箱地址是这个吗smallajax@foxmail.com

**Comment by yanzhenjie** [comment]
刚刚发布了2.0-alpha版本，我们公司已经在使用了，2.0变化比较大，你可以试试2.0，用流式API的实行提供了各种功能，包括视频选择，拍视频等。你说的问题已经修复了，有时间可以试试新版本。
