### ISSUE TITLE
activity中的匿名内部类中获取到activity对象

### ISSUE THREAD

**Issue by zypguhe** [yanzhenjie/Album#26]
你好，我遇到一种情况（版本1。0.3）：
Album.album(new MainActivity())//这里不能用this是因为在匿名内部类里
                        .requestCode(999)
                        .camera(true)
                        .selectCount(4)//选择图片的数量
                        .columnCount(3)//选择页面的图片列数
                        .title("选择图片")
                        .start();
这时候会报空指针。但是我用的1.0.0的版本时候却一切正常。能否给指点一下

**Comment by yanzhenjie** [comment]
`MainActivity.this`.

**Comment by zypguhe** [comment]
非常感谢，问题解决
