### ISSUE TITLE
图片预览

### ISSUE THREAD

**Issue by leif123** [yanzhenjie/Album#267]
设置标题栏背景颜色字体颜色不管用，一直是透明背景，白色字体。
用的com.yanzhenjie:album:2.1.3
 Album.galleryAlbum(this)
                                    .checkable(true)
                                    .checkedList(mAlbumFiles1)
                                    .currentPosition(position-1)
                                    .widget(
                                            Widget.newLightBuilder(this)
                                                    .toolBarColor(Color.RED)
                                                    .statusBarColor(Color.RED)
                                                    .mediaItemCheckSelector(Color.GREEN, Color.RED)
                                                    .bucketItemCheckSelector(Color.GREEN, Color.RED)
                                                    .buttonStyle(
                                                            Widget.ButtonStyle.newLightBuilder(this)
                                                                    .setButtonSelector(Color.WHITE, Color.GRAY)
                                                                    .build()
                                                    )
                                                    .build()
                                    )
                                    .onResult { result ->
                                        mAlbumFiles.clear()
                                        mAlbumFiles.add(addImage)
                                        mAlbumFiles.addAll(result)
                                        this.adapter.notifyDataSetChanged()
                                    }
                                    .start()
                        }

**Comment by yanzhenjie** [comment]
The title bar color cannot be set when the image is previewed.
