### ISSUE TITLE
Change default language to english

### ISSUE THREAD

**Issue by avaudagna** [yanzhenjie/Album#27]
Excellent library!!

Could you make english the default language to display in labels?

I tried overriding the strings.xml tags from my application but had no success.

Thanks!

**Comment by yanzhenjie** [comment]
I am preparing a new version, three to four hours after the release.

**Comment by avaudagna** [comment]
Or making the language of the app configurable? Like http://stackoverflow.com/a/32037685

In the initialization at AlbumConfig seems to be a good place.

**Comment by yanzhenjie** [comment]
The default language has been modified in English and the Locale configuration is provided. And the new version provides the camera's ability to use alone, Album will be getting better and better, thank you for your feedback.

**Comment by avaudagna** [comment]
Thank you!!

**Comment by issac-nabil** [comment]
thanks for support to this stage
now this lib have different bug 
if i changed app lang and open album activity it call locale method so app reverse to previous lang
in other way to explaing it if your lang in en and  open album after that change app lang to chines and open album app with back to english cause it will call locale method
i think solution to updae local in seprate method to call it when change app lang
thanks for support
