### ISSUE TITLE
请问是否有配置实现单选，即点了图片就自动完成

### ISSUE THREAD

**Issue by jayliang701** [yanzhenjie/Album#28]
如题。我只需要单选功能，把selectCount设置为1来使用，还是和多选一样的操作方式，感觉有点麻烦。必须得先进入图片打勾，返回，点完成才结束~~

请问是否有这样的配置可以设置？或者要怎么重写得以实现？

感谢作者的工作，这个库很棒。

**Comment by yanzhenjie** [comment]
就在一分钟前我提交了新版本：`1.0.4`，现在支持相机单独使用，不过暂时不支持你说的这个需求。不过修改也很简单，下载新版本代码，在`fragment`包下的`AlbumFragment`类的第`319`行代码后加这样一段代码即可：
```java
if(mAllowSelectCount == 1 && mCheckedImages.size() == 1) {
    onAlbumResult();
}
```

**Comment by yanzhenjie** [comment]
发布了新版本，支持了单选模式，既点击图片就返回，不用勾选并确认了。
