### ISSUE TITLE
期望新增功能:图片裁剪(方形,圆形)

### ISSUE THREAD

**Issue by 900326** [yanzhenjie/Album#287]
如果方便,期望增加图片裁剪(方形,圆形),裁剪框不动,底图滑动,缩放,跟底图不动,裁剪框可滑动,缩放,设置裁剪尺寸等相关功能,一直使用这个图库框架,经常遇到不同的裁剪需求,

**Comment by yanzhenjie** [comment]
目前没有这个计划，可以看一下这个库：
[https://github.com/yanzhenjie/Durban](https://github.com/yanzhenjie/Durban)
