### ISSUE TITLE
画廊可以旋转么

### ISSUE THREAD

**Issue by RuMengRen** [yanzhenjie/Album#32]
如题，保存下来的图片是反的

**Comment by yanzhenjie** [comment]
Album显示时会矫正图片角度的，会正确显示。但是比如小米某型号拍照的图片本身就是反的，拿到的角度就是0，所以程序上没法判断。

画廊不能旋转，如果相机拍照时正常的，返回给你的路径就是原来的绝对路径，你拿到后需要做角度判断，最好使用第三方成熟的loader加载。
