### ISSUE TITLE
Android 11 scoped storage support

### ISSUE THREAD

**Issue by fareed945** [yanzhenjie/Album#328]
Hey there ! First of all thanks for this beautiful library. I love everything of this.
Just wanted to check if we're planning of implementing it based on scoped storage rules of Android 10 and above ??
For now I've added the flag suggested by Google for it to work.
Thanks in advance

**Comment by bazimogmbh** [comment]
@fareed945 It already works very well respecting the scoped storage framework, you do not need the "requestLegacyExternalStorage" flag.

**Comment by fareed945** [comment]
Thanks for the reply !

**Comment by hejayeshj** [comment]
Audio recorded list files it returns wrong path(Uri). Any idea?
