### ISSUE TITLE
关于1.0.3升至1.0.5的两个小问题。

### ISSUE THREAD

**Issue by zypguhe** [yanzhenjie/Album#34]
1.在调用 Album.album(this)
                .requestCode(686)
                .title("选择图片")
                .camera(true)
                .selectCount(3)
                .columnCount(3)
                .camera(true)
                .start();
时，点击照相，此时会抛出异常，空指针。
2. Album.camera(this).requestCode(687).start();跳转至拍照页面，此时需要连续拍摄三次才能返回照片。同样的，连续按压三次返回按钮，才会返回上一个activity。

期待大神解答。（以上两个问题在1.0.3版本上是没有的）

**Comment by yanzhenjie** [comment]
你说的两个问题我这边做测试时都没有复现。  
第一个问题中，camera(true)你调用了两遍是无用的，不过不影响使用。请把你的异常信息贴出来一下，方便我修复。  
第二个问题，我这里换了几个手机都没复现，有没有可能是代码中调用了多次呢？  

另外，请把你项目的targetSdkVersiona贴一下，上述两个问题可能是手机型号不同导致，请把你使用的手机系统版本、手机品牌、品牌型号告知一下，方便我做测试。

谢谢反馈！

**Comment by zypguhe** [comment]
你好，我用的手机是魅族MX4 ，flyme6.0.2A     
   targetSdkVersion 25
第一个问题描述有点失误（不好意思）：应该是在拍照完成之后，返回上个Activity，在接收返回照片路径的时候，抛出异常（如下）：java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference

第二个问题：Album.camera(this).requestCode(687).start();并没有调用多次。
连续拍摄三次才能返回一张照片。

**Comment by yanzhenjie** [comment]
第一个异常信息太少了，不能判断是在哪里的错，第二个问题我再看看。

**Comment by fandayy** [comment]
第一个异常应该是拍照之后拿到的图片路径下的文件是null,我的解决方案是sleep一小会,等文件写入完成之后在获取图片文件

**Comment by fandayy** [comment]
@yanzhenjie  第一个异常应该是拍照之后拿到的图片路径下的文件是null,我的解决方案是sleep一小会,等文件写入完成之后在获取图片文件
