### ISSUE TITLE
某些系统调用相机拍照产生2张照片

### ISSUE THREAD

**Issue by linwill931121** [yanzhenjie/Album#35]
拍照时，会在DCIM目录下生成框架指定的 randomJPGPath()的文件，
同时会在DCIM/Canera目录下生成默认的IMG_XXXXX_XX.jpg.
因为EXTRA_OUTPUT不是标准方式，在某些系统上无法使用或者使用异常，
可以考虑正常拍照获取uri，再通过MediaStore.Image获取图片路径。

**Comment by yanzhenjie** [comment]
抱歉回的晚了，你说的情况在部分早期的手机上可能存在，但是至于EXTRA_OUTPUT非标准方式我不认同，由于部分开发者调用相机需指定路径，因此项目中还是维持现状！
