### ISSUE TITLE
小米5手机只用相册的功能，第二次进去会崩溃

### ISSUE THREAD

**Issue by misterdai520** [yanzhenjie/Album#42]

**Comment by yanzhenjie** [comment]
异常信息。

**Comment by Carey0732** [comment]
![image](https://cloud.githubusercontent.com/assets/19817192/26136932/8cedb83a-3af1-11e7-8bcc-599eef2ca890.png)

**Comment by Carey0732** [comment]
我用的也是小米5，有时候会出现这个问题

**Comment by yanzhenjie** [comment]
@Carey0723 你这个看不出来是Album的问题呀，我测试了小米5也没出现问题呢。
1. demo运行是否正常？  
2. 是否有其它异常情况呢？

**Comment by yanzhenjie** [comment]
已和提问者线下沟通，非Album的问题。
