### ISSUE TITLE
相册列表中的预览图显示不完整

### ISSUE THREAD

**Issue by ZYRzyr** [yanzhenjie/Album#47]
无论是demo apk还是我自己写的，都有一个问题：如果图片是长图，则预览列表中只会显示中间部分，如下第一排右边那张：
![1](https://cloud.githubusercontent.com/assets/13146645/26769519/2ba55c40-49e2-11e7-9c6a-0d0aa95359a9.png)
![2](https://cloud.githubusercontent.com/assets/13146645/26769520/2ba6ab86-49e2-11e7-8422-1da5e07c4d2c.png)
不知是故意这样做的还是有问题呢？其它长图也会有这种情况，试过小米红米4A（6.0），华为荣耀青春版（7.0）

**Comment by yanzhenjie** [comment]
长图在正方形的格子里面怎么全部显示呢？也许是我没明白你意思，你看下微信和QQ里面是否全部显示了，可以给一个图示出来，如果有问题我会发布一个新版！

**Comment by ZYRzyr** [comment]
sorry，我的锅，长图在正方形格子里如果全部显示的话可能会导致图片变形。
