### ISSUE TITLE
要是能在查看图片的时候隐藏掉Toolbar和下面选择的勾勾话，就perfect了

### ISSUE THREAD

**Issue by Gary15** [yanzhenjie/album#5]

**Comment by yanzhenjie** [comment]
预览大图的时候是吧，那时候应该也是可以选择的吧。如果需要的话你可以下载源码修改visibility.

**Comment by IdioticMadman** [comment]
@yanzhenjie 大神，隐藏toolbar和选择的勾应该问题不大，可以要怎么让图片也填充到statusbar呢。就像微信选择图片的时候，进入全屏的时候图片会填充到statusbar。有什么实现思路么？

**Comment by yanzhenjie** [comment]
可以实现的，我发布的时候时间紧就没加，也得改源码。

**Comment by IdioticMadman** [comment]
有没有比较好的实现思路呀，我要是设置flag的话，一滑动，statusbar就出来，然后5.0把布局填充到statusbar好像又不怎么实现的出来。。求大神指导

**Comment by yanzhenjie** [comment]
设置为全屏style，statusBar就不会出来了。

**Comment by IdioticMadman** [comment]
大神有没有空实现一下，设置style设置了好久，要么statusbar会变成白色，要不toolbar会填充到statusbar那里去了，没有空出statusbar的高度
