### ISSUE TITLE
支持视频混合选择吗，没看到视频啊

### ISSUE THREAD

**Issue by yummyChina** [yanzhenjie/Album#51]

**Comment by yanzhenjie** [comment]
已列为计划，我正在后期的版本中加入这个功能。

**Comment by yanzhenjie** [comment]
刚刚发布了2.0-alpha版本，我们公司已经在使用了，2.0变化比较大，你可以试试2.0，用流式API的实行提供了各种功能，包括视频选择，拍视频等。
