### ISSUE TITLE
Album画廊内存居高不下

### ISSUE THREAD

**Issue by flyjin** [yanzhenjie/Album#55]
在一个页面多次调用画廊 内存一直往上叠加 该页面销毁后 内存同样占用

**Comment by yanzhenjie** [comment]
我觉得这似乎没什么问题呀，系统还没开始回收呢，到了一定的时候它自然会来回收的，你可以试试一直点开关闭点开关闭，它总有降下来的时候。如果你觉得不安全，你可以配置自己的ImageLoader来加载图片。
