### ISSUE TITLE
toolbar与状态栏

### ISSUE THREAD

**Issue by sweet2o09** [yanzhenjie/Album#57]
你好,你的这个轻量级相册实在是太好用了,我能提几个小建议么:
1.如果能修改toolbar文字颜色跟字体大小就更好了
2.如果我的应用主色调是白色的话,能否支持修改状态栏上的文字颜色
3.查看图片的时候会有一层遮罩,把toolbar跟状态栏都遮盖住了,感觉不是很好看

**Comment by yanzhenjie** [comment]
这两天比较忙，周末我会尽快优化！

**Comment by sweet2o09** [comment]
你好,请问这个问题是否已经优化?现在是直接集成你的代码,自己修改的,使用的是https://github.com/gyf-dev/ImmersionBar这个工具

**Comment by yanzhenjie** [comment]
刚刚发布了2.0-alpha版本，支持白色状态栏，我们公司已经在使用了，2.0变化比较大，你可以试试2.0，用流式API的实行提供了各种功能，包括视频选择，拍视频等。

**Comment by sweet2o09** [comment]
好的,谢谢...Durban没更新么?
Album与Durban不是配合使用的么

**Comment by yanzhenjie** [comment]
Duban不用更新啊，还是一样的用法，只是需要遍历Album结果把path添加到新的ArrayList中给Durban 了。
