### ISSUE TITLE
toolbar和选中动画

### ISSUE THREAD

**Issue by ygeng** [yanzhenjie/Album#59]
严大，Album很好用，但是我发现一点点小瑕疵：
 1. 目前只能自定义toolbar和statusbar的颜色，不能更换toolbar的返回按钮，不能设置标题居中等等自定义toolbar内容；
 2. 查看选中的图片大图时，右下角的checkbox动画卡住不动，对勾出不来，不知道是不是个例。

严大加油！

**Comment by yanzhenjie** [comment]
新版可以更改StatusBar的颜色为白色了，刚刚发布了2.0-alpha版本，我们公司已经在使用了，2.0变化比较大，你可以试试2.0，用流式API的实行提供了各种功能，包括视频选择，拍视频等。

**Comment by ygeng** [comment]
好的 严大
