### ISSUE TITLE
后期会支持图片涂鸦么

### ISSUE THREAD

**Issue by IdioticMadman** [yanzhenjie/Album#6]

**Comment by IdioticMadman** [comment]
7.0上的文件读写权限貌似有问题
![image](https://cloud.githubusercontent.com/assets/16788980/20331291/7e20657e-abdf-11e6-8d30-c6ffde629814.png)

**Comment by yanzhenjie** [comment]
涂鸦和剪切是属于独立模块的，可能会添加module。7.0的这个问题我会尽快修复的，感谢反馈哈。

**Comment by yanzhenjie** [comment]
经过考虑，后期不考虑加入涂鸦，谢谢反馈。
