### ISSUE TITLE
安卓4.4闪退

### ISSUE THREAD

**Issue by cjcj125125** [yanzhenjie/Album#60]
严大大，你好，用你这个相册非常爽，然而4.4上直接报错，具体是类加载器not found ，求解
![qq 20170708133035](https://user-images.githubusercontent.com/20206579/27982884-a6488e18-63e1-11e7-883f-d539c68ca18f.png)    这个相册只支持4.4以上吗？

**Comment by jeonhei** [comment]
你是不是用了官方的MultiDex特性 如果是的话需要自己配置下编译规则和混淆规则 具体方法网上有

**Comment by yanzhenjie** [comment]
@jeonhei 正解。
