### ISSUE TITLE
在android7.0机器上，进入album后，返回到app，再打开其他activity就报错

### ISSUE THREAD

**Issue by cheukho** [yanzhenjie/Album#65]
在android7.0的设备上，只要start过album后，再回到app中打开其他activity（没有用到album的）app就会闪退。错误如下：
Attempt to invoke virtual method 'boolean java.util.Locale.equals(java.lang.Object)' on a null object reference
android.app.ActivityThread.updateLocaleListFromAppContext(ActivityThread.java:5556)

有谁遇过类似问题？麻烦指点一下

**Comment by cheukho** [comment]
clone demo是没有问题的，整合到app就出错，目前尚未定位到问题原因

**Comment by cheukho** [comment]
已经找到问题原因，国际化导致的。

// Language.
Locale locale = Album.getAlbumConfig().getLocale();
AlbumUtils.applyLanguageForContext(this, locale);

应该是我的app里面没有value-对应国家的文件夹

**Comment by yanzhenjie** [comment]
旧版本如果初始化了，要在初始化的时候设置Locale，不过新版修复了这个问题。刚刚发布了2.0-alpha版本，我们公司已经在使用了，2.0变化比较大，你可以试试2.0，用流式API的实行提供了各种功能，包括视频选择，拍视频等。

**Comment by liukai2530533** [comment]
2.0版本的视频录制完成之后等待有点慢，能不能转Loading或者提高编码速度

**Comment by yanzhenjie** [comment]
@liukai2530533 目前还没办法做到，那是系统自带相机行为。
