### ISSUE TITLE
在ViewPager中嵌套的Fragment中,OnActivityResult方法无法被调用

### ISSUE THREAD

**Issue by AndroidAndYang** [yanzhenjie/Album#67]
在ViewPager中嵌套的Fragment执行该操作Album.camera(getActivity()).requestCode(CAMERA_CODE).start();无法在OnActivityResult()方法接受到结果.请问该怎么解决

**Comment by yanzhenjie** [comment]
检查是否重写了`Activity#onActivityResult(int, int, Intent)`。
