### ISSUE TITLE
gallery画廊自定义GlideImageLoader报错

### ISSUE THREAD

**Issue by liukai2530533** [yanzhenjie/Album#68]
为了gallery画廊能展示网络图片  自定义了GlideImageLoader 并在Application注册。
public class GlideImageLoader implements AlbumImageLoader {
    @Override
    public void loadImage(ImageView imageView, String imagePath, int width, int height) {
        Glide.with(imageView.getContext())
                .load(imagePath)     //为了兼容网络图片直接加载imagePath
                .into(imageView);
    }
}

这样画廊功能能正常使用加载网络图片，然后在相册的界面也能正常的加载相册图片（不知道为什么就是没有LoaclImageLoader快）。问题来了----->  但是相册的界面展示出来之后再次点击选择相册报错闪退了。什么情况？
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.Locale.equals(java.lang.Object)' on a null object reference

**Comment by liukai2530533** [comment]
能不能分开设置ImageLoader.比如画廊用
Glide.with(imageView.getContext())
.load(imagePath) //为了兼容网络图片直接加载imagePath
.into(imageView);

相册用：
Glide.with(imageView.getContext())
.load(new File(imagePath)) 
.into(imageView);

**Comment by liukai2530533** [comment]
发现了问题：只要在Application中设置这个。再次选择相册就会报空指针？？
 Album.initialize(new AlbumConfig.Build()
                .setImageLoader(new GlideImageLoader()) // Use glide loader.
                .build());

**Comment by liukai2530533** [comment]
试过很多了 只要是设置了setImageLoader 不管是自定义的GlideImageLoader还是你自己LocalImageLoader  只要设置了 再次选择相册就会报错 或者说只要设置了setImageLoader  连调用Durban裁剪也会空指针

**Comment by liukai2530533** [comment]
看了一下你的源码 解决了 需要两个都设置
 Album.initialize(new AlbumConfig.Build()
                .setImageLoader(new LocalImageLoader())
                .setLocale(Locale.getDefault())
                .build()
        );

**Comment by yanzhenjie** [comment]
是的，新版当中修复了这个问题，刚刚发布了2.0-alpha版本，我们公司已经在使用了，2.0变化比较大，你可以试试2.0，用流式API的实行提供了各种功能，包括视频选择，拍视频等。
