### ISSUE TITLE
浏览已选图片时候点击取消选择，滑动后其它图片的选择框无法正常显示

### ISSUE THREAD

**Issue by ycads** [yanzhenjie/Album#69]
浏览已选图片时候点击取消选择，滑动后其它图片的选择框无法正常显示
不知道你们有没有这个问题。

**Comment by yanzhenjie** [comment]
暂时没有发现。刚刚发布了2.0-alpha版本，我们公司已经在使用了，2.0变化比较大，你可以试试2.0。
