### ISSUE TITLE
感觉设计的很有问题

### ISSUE THREAD

**Issue by flyjin** [yanzhenjie/Album#78]
选择图片返回的结果是一个ArrayList\<AlbumFile\>  而加载画廊确是ArrayList\<String\>  这个很郁闷
这导致从老版本升级到2.0相当麻烦  已经放弃
还有一点就是设置风格能不能统一设置? 比如在初始化里面设置? 每次都需要新建个widget传进去 很烦

**Comment by flyjin** [comment]
ArrayLis\\<AlbumFile\\>

**Comment by flyjin** [comment]
ArrayList<String>

**Comment by yanzhenjie** [comment]
谢谢你提的意见，不过你可能没有用Album，甚至都没看过Demo：
```java
Album.galleryAlbum(this)
...
```
