### ISSUE TITLE
Album.gallery(this)显示异常

### ISSUE THREAD

**Issue by wuyifengWYF** [yanzhenjie/Album#79]
我先把本地的图片拿出来放到一个集合.然后Album.gallery(this)这些图片.都是灰色.我随便跳到相册里 不管我选不选 回来之后 之前的图片就能看了 小米3 华为荣耀7都是这样 和权限和没关系 都有权限的

**Comment by ZQ173** [comment]
大兄弟我也遇到了，昨晚排查了好久，后面发现是 Loader 的问题，到你的 application 里面加上下面几句话就好了：

            Album.initialize(
                    AlbumConfig.newBuilder(this)
                            .setAlbumLoader(new GlideAlbumLoader()) // This is not necessary.
                            .setLocale(Locale.getDefault())
                            .build()
            );

ps：GlideAlbumLoader 在 demo 里面有。

**Comment by yanzhenjie** [comment]
我用2.0.0-alpha、2.0.0和2.0.1版本做了测试，都没有做初始化操作，也就是没有设置Loader，用嘴原始的Album，没有出现你们描述的问题。
