### ISSUE TITLE
图片做了压缩吗？

### ISSUE THREAD

**Issue by kenLaidiss** [yanzhenjie/Album#8]
选了几张图片，返回后在viewPager里面展示，然后页面就崩了

**Comment by yanzhenjie** [comment]
那个图片就是sd卡中原路径，建议你用fresco之类的工具加载。

**Comment by kenLaidiss** [comment]
用了fresco，完美解决！有个建议，就是拍照后，只有一张图片，希望可以在拍照后继续回到图片选择界面，而不是直接结束~望采纳！
