### ISSUE TITLE
android 5.0左右版本：在选中图片后，来回滑动所有图片选中和未选的，图标显示错误

### ISSUE THREAD

**Issue by xinlianzhu** [yanzhenjie/Album#80]
您好！我很喜欢这个图片选择的控件，感觉方便又实用！最近在测试的时候发现了一点小问题，希望能得到解答^_^ 具体如下：
android 5.0左右版本：在选中图片后，来回滑动所有图片选中和未选的，图标显示错误。
具体来说就是选中的应该是蓝色方框里有蓝色小对勾，实际变成了蓝色方框。
未选的应该是白色方框，实际变成了白色方框里有白色小对勾。
不知道其他人有没有遇到这个问题？

**Comment by yanzhenjie** [comment]
我们在测试中没有遇到，你可以通过widget设置选择框的颜色试试。
