### ISSUE TITLE
图片加载太慢啦

### ISSUE THREAD

**Issue by fmwcn** [yanzhenjie/Album#82]
对比其他开源库，基本都是秒加载，在700张左右的手机上大概需要6,7秒左右 ，小米6手机

**Comment by OvenCroc** [comment]
我也是同样的情况 , 图片少的时候速度还ok图片多了之后 , 进入相册的时间就会很长 , 大大些有没有什么好的解决办法啊

**Comment by yanzhenjie** [comment]
1. 2.0正式版已经发布，优化了这个问题，针对视频和图片必定返回预览图。

**Comment by yanzhenjie** [comment]
1. 2.0正式版已经发布，优化了打开Album时速度慢的问题，基本是毫秒级别打开。
2. 针对视频和图片必定返回预览图。  
3. 只要手机中的某个App使用了Album库并打开过，Album会为所有使用Album的App加快视频加载速度，毫秒级别加载，在视觉效果上看不出来**慢**。
4. 增加了Filter，可过滤文件大小、文件格式、视频时长，并且可以选择被过滤掉的文件是否显示。
