### ISSUE TITLE
How to put image in imageview?

### ISSUE THREAD

**Issue by AnthonyEd** [yanzhenjie/Album#86]
Please how do I put send image to Imageview without ActivityonResult and without data? Need an answer ASAP.

**Comment by fmwcn** [comment]
CallBack?

**Comment by AnthonyEd** [comment]
How? can someone please show me a code sample.

**Comment by yanzhenjie** [comment]
Sorry, I am not very aware of your problem, the following is some of the help I can provide.  

If you are using the 2.0 version, do not have onActivityResult, you can directly in the onResult () to get the results:  
```java
Album.album(this)
    ...
    .onResult(new Action<ArrayList<AlbumFile>>() {
        @Override
        public void onAction(int requestCode, @NonNull ArrayList<AlbumFile> result) {
        }
    })
    .onCancel(new Action<String>() {
        @Override
        public void onAction(int requestCode, @NonNull String result) {
        }
    })
    .start();
```

**Comment by yanzhenjie** [comment]
In addition:  
1. 2.0 stable version has been released, optimized to open the album when the slow problem, in a few milliseconds time to open.
2. For the video and pictures must return to the preview.
3. As long as the phone in an App using the Album library and opened, Album for all the use of Album App speed up the video load speed, loaded in a few milliseconds, in the visual effects can not see **slow**.
4. Added Filter, you can filter the file size, file format, video duration, and can choose to filter out the file is displayed.

**Comment by AnthonyEd** [comment]
What about "data"?

**Comment by yanzhenjie** [comment]
What data, I am not very understanding, sorry.

**Comment by AnthonyEd** [comment]
What about "data"? I am passing the Image from the Image gallery to the another activity's imageview.

**Comment by AnthonyEd** [comment]
how can I do that?

**Comment by yanzhenjie** [comment]
`onResult()` callback to the developer's data is `ArrayList<AlbumFile>` or `ArrayList<String>`, as to how to pass into any `Activity`, it depends entirely on the developer himself.

**Comment by AnthonyEd** [comment]
Please I need a code sample if possible.

**Comment by AnthonyEd** [comment]
Would I use intent and Uri? But there is no data, please show me an example because I don't understand.

**Comment by yanzhenjie** [comment]
Have you seen the sample provided by Album ?

**Comment by AnthonyEd** [comment]
yes.

**Comment by AnthonyEd** [comment]
OK, but can you just give me a simple example of how to put the selected image on an imageview.

**Comment by yanzhenjie** [comment]
Here are some examples that hope can help you:
```java
// Sample 1. If here to preview the original picture, but not allow users to choose.
ArrayList<String> imageList = new ArrayList<>();
Album.gallery(getContext())
    .checkedList(imageList)
    .checkable(false)
    .start();

// Sample 2. This is optional and we can accept the results of user selection.
ArrayList<String> imageList = new ArrayList<>();
Album.gallery(getContext())
    .checkedList(imageList)
    .checkable(true)
    .onResult(new Action<ArrayList<String>>() {
        @Override
        public void onAction(int i, @NonNull ArrayList<String> strings) {
            ArrayList<String> newImageList = strings;
            Intent intent = new Intent(getContext(), GoodsActivity.class);
            intent.putStringArrayListExtra("image_list", newImageList);
            getContext().startActivity(intent);
        }
    })
    .start();

// Sample 3. User select the picture.
Album.image(getContext())
    .multipleChoice()
    .onResult(new Action<ArrayList<AlbumFile>>() {
        @Override
        public void onAction(int i, @NonNull ArrayList<AlbumFile> albumFiles) {
            ArrayList<String> newImageList = new ArrayList<>();
            for (AlbumFile albumFile : albumFiles) {
                newImageList.add(albumFile.getPath());
            }

            Intent intent = new Intent(getContext(), GoodsActivity.class);
            intent.putStringArrayListExtra("image_list", newImageList);
            getContext().startActivity(intent);
        }
    })
    .start();
```

**Comment by yanzhenjie** [comment]
More sample you can see sample or `ReadMe`.

**Comment by AnthonyEd** [comment]
Thanks.

**Comment by AnthonyEd** [comment]
I have been trying to get the image from the other activity but it didn't work. Here is my code.
`       Intent intent = getIntent();
        Bitmap bitmap = intent.getStringArrayListExtra("Image");
        FinalImageView.setImageBitmap(bitmap);
`

**Comment by AnthonyEd** [comment]
Please help me resolve this issue.

**Comment by yanzhenjie** [comment]
For example, this piece of code:
```java
ArrayList<String> newImageList = new ArrayList<>();
for (AlbumFile albumFile : albumFiles) {
    newImageList.add(albumFile.getPath());
}

Intent intent = new Intent(getContext(), GoodsActivity.class);
intent.putStringArrayListExtra("image_list", newImageList);
getContext().startActivity(intent);
```
ArrayList here is the path of the local image, you need to load the image according to the path, for example, using Glide, ImageLoader or Fresco, such as:
```java
Glide.with(getContext())
    .load(imagePath)
    .into(mIvUserAvatar);
```
If you still have questions, please continue to reply to this question.

**Comment by AnthonyEd** [comment]
Please what should I put in the ".load()".

**Comment by yanzhenjie** [comment]
Should pass in the file path, local or network path. Please refer to:  
[Glide](https://github.com/bumptech/glide)  
[Fresco](https://github.com/facebook/fresco)

**Comment by AnthonyEd** [comment]
Please can you tell me th galley path because I want to get the chosen image from the gallery, just one image. O r if you've done this before can you please show me a full code sample.

**Comment by yanzhenjie** [comment]
Above has given a detailed example, as well as the process, I think you should not continue to have this question.
