### ISSUE TITLE
手机图片多的时候加载特别慢！能不能加入缓存？

### ISSUE THREAD

**Issue by lexluthors** [yanzhenjie/Album#87]
手机有1000多张图片，每次进入都加载好久，太慢了。能不能加入缓存呢？希望作者优化这一块。因为大部分人手机还是有很多图片的。

**Comment by yanzhenjie** [comment]
1. 2.0正式版已经发布，优化了打开Album时速度慢的问题，基本是毫秒级别打开。
2. 针对视频和图片必定返回预览图。  
3. 只要手机中的某个App使用了Album库并打开过，Album会为所有使用Album的App加快视频加载速度，毫秒级别加载，在视觉效果上看不出来**慢**。
4. 增加了Filter，可过滤文件大小、文件格式、视频时长，并且可以选择被过滤掉的文件是否显示。
