### ISSUE TITLE
图片加载时间长

### ISSUE THREAD

**Issue by lihaodong** [yanzhenjie/Album#88]
手机内有2000多张图片，加载时间在30秒左右，每次进入图片都会重新加载

**Comment by 52932** [comment]
我的也是

**Comment by yanzhenjie** [comment]
了解了，在2.0正式版中会优化掉，明后天发布新版本。

**Comment by ruanbaojun1105** [comment]
刚才还打算换库，既然要更新我就再等你两天吧

**Comment by ruanbaojun1105** [comment]
讲真，还没更新

**Comment by liukai2530533** [comment]
加载图片。为什么2.0的版本比1.0的版本要慢呢。还要转Loading  我用的1.0版本 很快就打开没有Loading.快很多

**Comment by ruanbaojun1105** [comment]
已换，谢谢

**Comment by lihaodong** [comment]
2.0获取图片的信息比较多，

**Comment by cizkey** [comment]
严大...还没更新啊.....这个加载很久很要命啊

**Comment by yanzhenjie** [comment]
1. 2.0正式版已经发布，优化了打开Album时速度慢的问题，基本是毫秒级别打开。
2. 针对视频和图片必定返回预览图。  
3. 只要手机中的某个App使用了Album库并打开过，Album会为所有使用Album的App加快视频加载速度，毫秒级别加载，在视觉效果上看不出来**慢**。
4. 增加了Filter，可过滤文件大小、文件格式、视频时长，并且可以选择被过滤掉的文件是否显示。
