### ISSUE TITLE
cordova 插件

### ISSUE THREAD

**Issue by cosdy** [yanzhenjie/album#9]
将其做成cordova插件后发现其它都正常，但是打开大图预览时，页面没有全屏，四周有边距，您有没有cordova插件版？
![screenshot_2016-12-16-13-07-11-31](https://cloud.githubusercontent.com/assets/3700864/21252402/675b3d2c-c391-11e6-8ce5-0ffcd78a8311.png)

**Comment by cosdy** [comment]
这是什么原因，为什么会有边距？

**Comment by yanzhenjie** [comment]
我没有cordova插件版本，可能是dialog style引起，你那边是否可以修改dialog style试试。

**Comment by cosdy** [comment]
谢谢, 我试试

**Comment by cosdy** [comment]
是album_dialog_album_preview.xml文件对应的AlbumDialogStyle.Preview吗？

**Comment by yanzhenjie** [comment]
是的。

**Comment by cosdy** [comment]
添加了 <item name="android:windowFullscreen">true</item> 还是不行，能否给点提示？

**Comment by cosdy** [comment]
您有没有编译好的library？library怎么调用？
