### ISSUE TITLE
Very slow initial load of Album

### ISSUE THREAD

**Issue by bazimogmbh** [yanzhenjie/Album#90]
After migration to 2.0.0 alpha from 1.0.7, the Album loads very very slowly.

**Comment by yangkile** [comment]
if you want quickly
in this com.yanzhenjie.album.task.MediaReader file,delete this code


![image](https://user-images.githubusercontent.com/18137686/30796124-52f530ee-a203-11e7-80ff-db5ed867f0d1.png)

**Comment by mwj1103** [comment]
我删除了那段代码，没有提高多少，原来是4s左右

**Comment by yanzhenjie** [comment]
1. 2.0 stable version has been released, optimized to open the album when the slow problem, in a few milliseconds time to open.
2. For the video and pictures must return to the preview.
3. As long as the phone in an App using the Album library and opened, Album for all the use of Album App speed up the video load speed, loaded in a few milliseconds, in the visual effects can not see **slow**.
4. Added Filter, you can filter the file size, file format, video duration, and can choose to filter out the file is displayed.
----
1. 2.0正式版已经发布，优化了打开Album时速度慢的问题，基本是毫秒级别打开。
2. 针对视频和图片必定返回预览图。  
3. 只要手机中的某个App使用了Album库并打开过，Album会为所有使用Album的App加快视频加载速度，毫秒级别加载，在视觉效果上看不出来**慢**。
4. 增加了Filter，可过滤文件大小、文件格式、视频时长，并且可以选择被过滤掉的文件是否显示。
