### ISSUE TITLE
Matisse的功能没你多，看好你！

### ISSUE THREAD

**Issue by liukai2530533** [yanzhenjie/Album#92]
别的库加载是快，但是我是真爱。坐等更新加载图片取消Loading等待。顺便问个问题，gallery中支持长按点击事件吗？比如长按点击提示下载图片？

**Comment by yanzhenjie** [comment]
1. 2.0正式版已经发布，优化了打开Album时速度慢的问题，基本是毫秒级别打开。
2. 针对视频和图片必定返回预览图。  
3. 只要手机中的某个App使用了Album库并打开过，Album会为所有使用Album的App加快视频加载速度，毫秒级别加载，在视觉效果上看不出来**慢**。
4. 增加了Filter，可过滤文件大小、文件格式、视频时长，并且可以选择被过滤掉的文件是否显示。
