### ISSUE TITLE
当SD卡里面很多图片跟目录的时候,唤起Album相册很慢

### ISSUE THREAD

**Issue by sweet2o09** [yanzhenjie/Album#93]
当SD卡里面很多图片跟目录的时候,唤起Album相册很慢,一般都要等个10几秒,有时候还会卡在那边,使用的是小米5s手机,应该不算太差...

**Comment by liukai2530533** [comment]
先用1.0版本吧

**Comment by sweet2o09** [comment]
2.0版本已经用了一段时间了...现在回退回1.0有些麻烦...=.=!!

**Comment by cizkey** [comment]
希望大佬赶快解决啊. 这个真的很慢.

**Comment by yanzhenjie** [comment]
1. 2.0正式版已经发布，优化了打开Album时速度慢的问题，基本是毫秒级别打开。
2. 针对视频和图片必定返回预览图。  
3. 只要手机中的某个App使用了Album库并打开过，Album会为所有使用Album的App加快视频加载速度，毫秒级别加载，在视觉效果上看不出来**慢**。
4. 增加了Filter，可过滤文件大小、文件格式、视频时长，并且可以选择被过滤掉的文件是否显示。

**Comment by sweet2o09** [comment]
棒棒哒
