### ISSUE TITLE
问个问题..

### ISSUE THREAD

**Issue by m122469119** [yanzhenjie/Album#96]
读了下源码,之前图片加载慢的原因是因为获取图片的时候去查询了图片的缩略图,现在改成了图片选择完后再去获取图片的缩略图,但是我有一点不是很懂,为什么要去获取这张缩略图呢?请问哥们你是在什么样的场景需要这样的需求的?

**Comment by m122469119** [comment]
一时没转过弯,感觉问了多余的问题..压缩图片上传..之前我改的也是获取图片集合后才进行压缩

**Comment by yanzhenjie** [comment]
我并不需要这个，其它使用Album的开发者需要。
