### ISSUE TITLE
本地SD卡下生成AlbumCache

### ISSUE THREAD

**Issue by sweet2o09** [yanzhenjie/Album#97]
你好,之前有提了个相册加载慢的问题,现在新版本非常流畅,十分感谢
不过在使用新版本的时候发现在SD卡下会有一个AlbumCache目录,里面会保存一些照片,
然后再次打开相册的时候就会发现很多重复的照片,
不知道AlbumCache目录具体是干什么用的?
能否在唤起相册的时候屏蔽掉该目录或者其他什么办法解决因为AlbumCache目录导致的相册出现重复图片的问题

**Comment by yanzhenjie** [comment]
发布了一个2.0.1版本，忘记评论给你了。
